=== Apress/foundation-xml-for-flash/chapter07/authorDocuments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="qryAuthorDocuments" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="qryAuthorDocuments">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="AuthorFirstName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AuthorLastName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AuthorOrganisation" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="documentName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="200"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="documentPublishYear" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Apress/foundation-xml-for-flash/chapter07/authorDocuments.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="authorDocuments.xsd" generated="2005-06-02T06:36:28">
<qryAuthorDocuments>
<AuthorFirstName>Alison</AuthorFirstName>
<AuthorLastName>Ambrose</AuthorLastName>
<AuthorOrganisation>Organization A</AuthorOrganisation>
<documentName>Fishing tips</documentName>
<documentPublishYear>1999</documentPublishYear>
</qryAuthorDocuments>
<qryAuthorDocuments>
<AuthorFirstName>Alison</AuthorFirstName>
<AuthorLastName>Ambrose</AuthorLastName>
<AuthorOrganisation>Organization A</AuthorOrganisation>
<documentName>Shopping for profit and pleasure</documentName>
<documentPublishYear>2002</documentPublishYear>
</qryAuthorDocuments>
<qryAuthorDocuments>
<AuthorFirstName>Douglas</AuthorFirstName>
<AuthorLastName>Donaldson</AuthorLastName>
<AuthorOrganisation>Organization B</AuthorOrganisation>
<documentName>Outstanding dinner parties</documentName>
<documentPublishYear>2003</documentPublishYear>
</qryAuthorDocuments>
<qryAuthorDocuments>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganisation>Organization C</AuthorOrganisation>
<documentName>Bikes as an alternative source of transport</documentName>
<documentPublishYear>2004</documentPublishYear>
</qryAuthorDocuments>
<qryAuthorDocuments>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganisation>Organization C</AuthorOrganisation>
<documentName>Entertaining ways</documentName>
<documentPublishYear>2000</documentPublishYear>
</qryAuthorDocuments>
<qryAuthorDocuments>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganisation>Organization C</AuthorOrganisation>
<documentName>Growing radishes</documentName>
<documentPublishYear>2001</documentPublishYear>
</qryAuthorDocuments>
<qryAuthorDocuments>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganisation>Organization C</AuthorOrganisation>
<documentName>Growing tulips</documentName>
<documentPublishYear>2002</documentPublishYear>
</qryAuthorDocuments>
<qryAuthorDocuments>
<AuthorFirstName>Saul</AuthorFirstName>
<AuthorLastName>Sorenson</AuthorLastName>
<AuthorOrganisation>Organization D</AuthorOrganisation>
<documentName>Bike riding for non-bike riders</documentName>
<documentPublishYear>2004</documentPublishYear>
</qryAuthorDocuments>
</dataroot>
