=== Apress/foundation-xml-for-flash/chapter03/accessQryBookDetailsExport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
	<xsd:element name="dataroot">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="qryBookDetails" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="generated" type="xsd:dateTime"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="qryBookDetails">
		<xsd:annotation>
			<xsd:appinfo/>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="documentID" type="xsd:int" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes"/>
				<xsd:element name="documentName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="200"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="authorID" type="xsd:int" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes"/>
				<xsd:element name="AuthorFirstName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="50"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="AuthorLastName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="50"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="AuthorOrganization" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="50"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="documentPublishYear" type="xsd:short" minOccurs="0" od:jetType="integer" od:sqlSType="smallint"/>
				<xsd:element name="categoryID" type="xsd:int" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes"/>
				<xsd:element name="category" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="50"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Apress/foundation-xml-for-flash/chapter03/accessQryBookDetailsExport.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="accessQryBookDetailsExport.xsd" generated="2005-03-04T18:50:47">
<qryBookDetails>
<documentID>2</documentID>
<documentName>Bike riding for non-bike riders</documentName>
<authorID>4</authorID>
<AuthorFirstName>Saul</AuthorFirstName>
<AuthorLastName>Sorenson</AuthorLastName>
<AuthorOrganization>Organization D</AuthorOrganization>
<documentPublishYear>2004</documentPublishYear>
<categoryID>5</categoryID>
<category>Bike riding</category>
</qryBookDetails>
<qryBookDetails>
<documentID>3</documentID>
<documentName>Bikes as an alternative source of transport</documentName>
<authorID>3</authorID>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganization>Organization C</AuthorOrganization>
<documentPublishYear>2004</documentPublishYear>
<categoryID>5</categoryID>
<category>Bike riding</category>
</qryBookDetails>
<qryBookDetails>
<documentID>6</documentID>
<documentName>Entertaining ways</documentName>
<authorID>3</authorID>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganization>Organization C</AuthorOrganization>
<documentPublishYear>2000</documentPublishYear>
<categoryID>3</categoryID>
<category>Cooking</category>
</qryBookDetails>
<qryBookDetails>
<documentID>4</documentID>
<documentName>Fishing tips</documentName>
<authorID>1</authorID>
<AuthorFirstName>Alison</AuthorFirstName>
<AuthorLastName>Ambrose</AuthorLastName>
<AuthorOrganization>Organization A</AuthorOrganization>
<documentPublishYear>1999</documentPublishYear>
<categoryID>1</categoryID>
<category>Fishing</category>
</qryBookDetails>
<qryBookDetails>
<documentID>7</documentID>
<documentName>Growing radishes</documentName>
<authorID>3</authorID>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganization>Organization C</AuthorOrganization>
<documentPublishYear>2001</documentPublishYear>
<categoryID>2</categoryID>
<category>Gardening</category>
</qryBookDetails>
<qryBookDetails>
<documentID>8</documentID>
<documentName>Growing tulips</documentName>
<authorID>3</authorID>
<AuthorFirstName>Lucinda</AuthorFirstName>
<AuthorLastName>Larcombe</AuthorLastName>
<AuthorOrganization>Organization C</AuthorOrganization>
<documentPublishYear>2002</documentPublishYear>
<categoryID>2</categoryID>
<category>Gardening</category>
</qryBookDetails>
<qryBookDetails>
<documentID>5</documentID>
<documentName>Outstanding dinner parties</documentName>
<authorID>2</authorID>
<AuthorFirstName>Douglas</AuthorFirstName>
<AuthorLastName>Donaldson</AuthorLastName>
<AuthorOrganization>Organization B</AuthorOrganization>
<documentPublishYear>2003</documentPublishYear>
<categoryID>3</categoryID>
<category>Cooking</category>
</qryBookDetails>
<qryBookDetails>
<documentID>1</documentID>
<documentName>Shopping for profit and pleasure</documentName>
<authorID>1</authorID>
<AuthorFirstName>Alison</AuthorFirstName>
<AuthorLastName>Ambrose</AuthorLastName>
<AuthorOrganization>Organization A</AuthorOrganization>
<documentPublishYear>2002</documentPublishYear>
<categoryID>4</categoryID>
<category>Shopping</category>
</qryBookDetails>
</dataroot>
