=== Apress/foundation-xml-for-flash/chapter03/addressSchema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="phoneBook">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="contact" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="contact">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string"/>
				<xsd:element name="address" type="xsd:string"/>
				<xsd:element name="phone" type="xsd:string"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:integer" use="required"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Apress/foundation-xml-for-flash/chapter03/address.xml
<?xml version="1.0" encoding="UTF-8"?>
<phoneBook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="addressSchema.xsd">
	<contact id="1">
		<name>Sas Jacobs</name>
		<address>123 Some Street, Some City, Some Country</address>
		<phone>123 456</phone>
	</contact>
	<contact id="2">
		<name>John Smith</name>
		<address>4 Another Street, Another City, Another Country</address>
		<phone>456 789</phone>
	</contact>
	<contact id="3">
		<name>Jo Bloggs</name>
		<address>7 Different Street, Different City, UK</address>
		<phone>789 123</phone>
	</contact>
</phoneBook>
